
'use strict';
const CONFIG=window.SEC1_CONFIG;
const IS_LIFF=window.SEC1_PAGE_LIFF===true;
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>new Intl.NumberFormat('th-TH',{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(n)||0)+' ฿';
const day=d=>d?new Date(d).toLocaleDateString('th-TH',{day:'numeric',month:'short',year:'numeric',timeZone:'Asia/Bangkok'}):'—';
const rid=()=>crypto.randomUUID();
const NAMES={'my-bills':'บิลของฉัน','open-bills':'บิลที่กำลังเรียกเก็บ',summary:'สรุปยอดเงิน',expenses:'รายจ่ายทั้งหมด',history:'ประวัติของฉัน','create-bill':'สร้างบิล','create-withdrawal':'บันทึกถอนเงิน',plans:'แผนรายเดือน',reviews:'ตรวจสลิป',notifications:'สถานะการแจ้งเตือน','bill-detail':'รายละเอียดบิล',payment:'ชำระบิล'};
const ICONS={'my-bills':'M6 3h12v18l-3-2-3 2-3-2-3 2z M9 8h6 M9 12h6','open-bills':'M3 10v4h4l11 5V5L7 10z M7 14l2 7',summary:'M3 7h18v14H3z M3 7V4h15 M16 12h5v5h-5z',expenses:'M4 6h16v15H4z M8 6V3h8v3 M8 11h8 M8 15h5',history:'M3 12a9 9 0 1 0 3-7 M3 3v6h6 M12 7v5l3 2',plans:'M4 5h16v16H4z M8 2v6 M16 2v6 M4 10h16',reviews:'M10 18a8 8 0 1 0 0-16 8 8 0 0 0 0 16 M16 16l6 6',notifications:'M5 17V9a7 7 0 0 1 14 0v8l2 2H3z M9 22h6'};
const icon=k=>`<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${ICONS[k]||'M12 4v16 M4 12h16'}"/></svg>`;
const hero=(title,sub)=>`<div class="hero"><div><span class="tag">CHICKEN CLUB</span><h2 style="margin-top:12px">${esc(title)}</h2><p>${esc(sub)}</p></div>${mascot()}</div>`;
let session=null,token='',view='my-bills',page=1,billId='',data=null,seq=0,busy=false;
function route(){const u=new URL(location.href),extra=u.searchParams.get('liff.state');let p=u.searchParams;if(extra){let e=extra;try{e=decodeURIComponent(e)}catch(_){}const q=e.indexOf('?');const more=new URLSearchParams(q>=0?e.slice(q+1):e.replace(/^\//,''));more.forEach((v,k)=>{if(!p.has(k))p.set(k,v)});}billId=p.get('billId')||'';view=billId?(p.get('view')==='bill-detail'?'bill-detail':'payment'):(NAMES[p.get('view')]?p.get('view'):'my-bills');}
function nav(){const keys=['my-bills','open-bills','summary','expenses','history'];if(session?.isAdmin)keys.push('create-bill','plans','create-withdrawal','reviews','notifications');$('#nav').innerHTML=keys.map(k=>`<button data-view="${k}" class="${view===k?'active':''}">${icon(k)}${NAMES[k]}</button>`).join('');$('#nav').querySelectorAll('button').forEach(b=>b.onclick=()=>{if(!busy)load(b.dataset.view)});}
function skeleton(){return '<div style="margin-top:24px"><div class="skeleton short"></div><div class="cards"><div class="skeleton"></div><div class="skeleton"></div><div class="skeleton"></div><div class="skeleton"></div></div><p class="muted">กำลังอ่านข้อมูลล่าสุด…</p></div>';}
function error(e){$('#content').innerHTML=`<div class="notice error">${esc(e.message||e)}</div><button class="btn soft" id="retry">ลองโหลดอีกครั้ง</button>`;$('#retry').onclick=()=>load(view,page,billId);}
async function ask(title,html){$('#dialogTitle').textContent=title;$('#dialogBody').innerHTML=html;$('#modal').showModal();return new Promise(resolve=>{let done=false;function finish(v){if(done)return;done=true;$('#modal').close();resolve(v)}$('#dialogYes').onclick=()=>finish(true);$('#dialogNo').onclick=()=>finish(false);$('#modal').oncancel=e=>{e.preventDefault();finish(false)}})}
function empty(text){return `<div class="card empty"><div class="face">🐣</div><h3>${esc(text)}</h3><p class="muted">ไก่จิก พร้อมช่วยเมื่อมีรายการครับ</p></div>`;}
function pager(h){if(!h||h.pages<=1)return;$('#content').insertAdjacentHTML('beforeend',`<div class="pager"><button class="btn soft" id="prev" ${h.hasPrevious?'':'disabled'}>ก่อนหน้า</button><span>${h.page} / ${h.pages}</span><button class="btn soft" id="next" ${h.hasNext?'':'disabled'}>ถัดไป</button></div>`);$('#prev').onclick=()=>load(view,h.page-1,billId);$('#next').onclick=()=>load(view,h.page+1,billId);}
function render(){if(view==='summary')return summary();if(view==='create-bill')return createBill();if(view==='create-withdrawal')return withdrawal();if(view==='payment')return payment();if(view==='bill-detail')return billDetail();if(view==='plans')return plans();if(view==='reviews')return reviews();if(view==='notifications')return notifications();if(view==='expenses'||view==='history')return renderHistory();bills();}
function summary(){const s=data.financeSummary;$('#content').innerHTML=hero('รังออมตังของทีม วันนี้เป็นอย่างไร?','ยอดรับ รายจ่าย และยอดถอน อัปเดตจากบัญชีของทีม')+`<div class="metrics">${[['คงเหลือสุทธิ',s.balance],['รับทั้งหมด',s.income],['ยอดค้างรับ',s.outstanding],['รายจ่าย',s.expenses],['ถอนนำไปใช้',s.withdrawn]].map(([t,n])=>`<div class="metric"><div class="muted">${t}</div><div class="value">${money(n)}</div></div>`).join('')}</div><div class="notice">สลิปที่รอตรวจสอบยังไม่นับเป็นเงินรับ จน Admin ยืนยันเงินเข้าแล้ว</div>`;}
function bills(){const h=data.history;$('#content').innerHTML=hero(view==='my-bills'?'เช็กบิลแล้ว สบายใจได้เลย':'เก็บเงินด้วยกัน โปร่งใสทุกบิล','ยอดที่แสดงเป็นยอดล่าสุด กดเปิดบิลเพื่อส่งหลักฐานได้ทันที')+(h.items.length?`<div class="cards">${h.items.map(b=>{const paid=b.paymentStatus==='paid',late=new Date(b.dueDate)<new Date(),sub=(data.submissions||[]).find(s=>s.billId===b.id);return `<article class="card fade"><div class="bill-head"><span class="tag ${paid?'paid':late?'warn':''}">${b.billType==='monthly'?'รายเดือน':'กิจกรรม'}</span><span class="face">${paid?'🥳':late?'😤':'🥺'}</span></div><h3>${esc(b.title)}</h3><p class="muted">ครบกำหนด ${day(b.dueDate)}</p><div class="amount">${money(view==='my-bills'?Math.max(0,b.amount-b.paidAmount):b.outstanding)}</div><p class="small muted">${paid?'ชำระครบแล้ว ขอบคุณครับ':sub?'หลักฐาน: '+status(sub.status):'ยอดคงเหลือที่เรียกเก็บ'}</p><div class="progress"><span style="width:${Math.min(100,Math.max(0,(b.paidCount/Math.max(1,b.memberCount))*100))}%"></span></div><p class="muted">ชำระแล้ว ${b.paidCount} / ${b.memberCount} คน</p><button class="btn soft full" data-pay="${esc(b.id)}">${icon('my-bills')}เปิดรายละเอียดบิล</button>${session.isAdmin&&b.status==='open'?`<button class="btn soft full" style="margin-top:8px" data-remind="${esc(b.id)}">แจ้งเตือนผู้ค้าง</button>`:''}</article>`}).join('')}</div>`:empty('ยังไม่มีบิลในรายการนี้'));document.querySelectorAll('[data-pay]').forEach(btn=>btn.onclick=()=>load(view==='open-bills'?'bill-detail':'payment',1,btn.dataset.pay));document.querySelectorAll('[data-remind]').forEach(btn=>btn.onclick=async()=>{if(await ask('แจ้งเตือนบิลนี้','<p>ส่งเฉพาะผู้ค้าง ช่องทางที่ส่งแล้ววันนี้จะถูกข้าม</p>'))mutate(btn,'secRemind',{billId:btn.dataset.remind},r=>ask('ผลการส่ง',`<p>LINE รับคำขอ ${r.accepted} • ล้มเหลว ${r.failed} • ข้าม ${r.skipped}</p>`))});pager(h);}
function billDetail(){const b=data.bill;$('#content').innerHTML=hero(b.title,'ชำระแล้ว '+b.paidCount+' / '+b.memberCount+' คน')+`<div class=card>${data.members.map(m=>`<div class=table-row><span>${esc(m.memberName)} <small>${m.status==='paid'?'🥳 ชำระแล้ว':'🥺 ค้างชำระ'}</small></span><strong>${money(Math.max(0,m.amount-m.paidAmount))}</strong></div>`).join('')}${data.canPay?'<button class=btn id=payDetail>เปิดบิลของฉันเพื่อส่งสลิป</button>':''}</div>`;if($('#payDetail'))$('#payDetail').onclick=()=>load('payment',1,b.id);}
function status(s){return ({draft:'ตรวจข้อมูลก่อนส่ง',pending:'รอ Admin ตรวจสอบ',posting:'กำลังลงบัญชี',approved:'อนุมัติแล้ว',rejected:'ไม่ผ่าน',accepted:'LINE รับคำขอแล้ว',failed:'ส่งล้มเหลว',sending:'กำลังส่ง'})[s]||s;}
function renderHistory(){const h=data.history;$('#content').innerHTML=hero(view==='expenses'?'เงินทุกบาท เล่าเรื่องได้':'ประวัติการชำระของคุณ',view==='expenses'?'ดูว่าใช้เงินกับอะไร เมื่อไหร่ และจำนวนเท่าไร':'รายการที่ได้รับการยืนยันแล้ว')+(h.items.length?`<div class="card">${h.items.map(x=>`<div class="table-row"><div><h3>${esc(x.title)}</h3><p class="muted">${day(x.date)} • ${view==='expenses'?(x.kind==='withdrawal'?'ถอนนำไปใช้':'รายจ่าย'):'ชำระเงิน'}</p></div><strong>${money(x.amount)}</strong></div>`).join('')}</div>`:empty('ยังไม่มีประวัติ'));pager(h);}
function membersForm(m){return `<div class="wide"><div class="row between"><h3>สมาชิกที่เรียกเก็บ</h3><button type="button" class="btn soft" id="all">เลือกทั้งหมด</button></div><div class="members">${m.map(x=>`<label><input type="checkbox" name="member" value="${esc(x.id)}">${esc(x.name)}</label>`).join('')}</div></div>`;}
function createBill(){const requestId=rid();$('#content').innerHTML=hero('สร้างบิล ให้รังออมตังดูแลต่อ','เลือกสมาชิก ตั้งยอดต่อคน และวันครบกำหนด')+`<form id="form" class="card formgrid"><label>ประเภท<select name="billType"><option value="activity">กิจกรรมเฉพาะกิจ</option><option value="monthly">แผนรายเดือน</option></select></label><label>ยอดต่อคน<input name="amountPerMember" type="number" min="0.01" step="0.01" required></label><label class="wide">ชื่อบิล<input name="title" maxlength="100" required></label><label id="dueLabel">วันครบกำหนด<input name="dueDate" type="date" required value="${esc(data.today)}"></label><label id="monthlyLabel" class="hide">วันที่ครบกำหนดในเดือน<input name="dueDay" type="number" min="23" max="28" value="28"></label>${membersForm(data.members)}<label class="wide">หมายเหตุ<textarea name="note" rows="2"></textarea></label><div class="wide notice">รายเดือนสร้างบิลในวันที่ 23–28 และตรวจแจ้งเตือนวันละครั้ง มีรอบสำรองสำหรับช่องทางที่ล้มเหลว</div><button class="btn wide">สร้างรายการ</button><div class="wide" id="formError"></div></form>`;const f=$('#form');f.billType.onchange=()=>{const m=f.billType.value==='monthly';$('#dueLabel').classList.toggle('hide',m);$('#monthlyLabel').classList.toggle('hide',!m);f.dueDate.required=!m};$('#all').onclick=()=>{const inputs=[...f.querySelectorAll('[name=member]')],checked=inputs.every(i=>i.checked);inputs.forEach(i=>i.checked=!checked)};f.onsubmit=e=>{e.preventDefault();const b=Object.fromEntries(new FormData(f));b.memberIds=[...f.querySelectorAll('[name=member]:checked')].map(i=>i.value);if(!b.memberIds.length){$('#formError').textContent='เลือกสมาชิกอย่างน้อยหนึ่งคน';return}mutate(f.querySelector('button[type=submit]')||f.querySelector('.btn.wide'),'secCreate',{...b,requestId},()=>load(b.billType==='monthly'?'plans':'open-bills'))};}
function fileForm(){return '<label class="drop wide">📷 เลือกรูปหลักฐาน<input id="file" type="file" accept="image/jpeg,image/png,image/webp" required><span class="muted">ย่อรูปก่อนส่ง โดยคงรายละเอียดสลิป</span></label><img id="preview" class="preview hide wide" alt="ตัวอย่างหลักฐาน">';}
async function compress(file){if(file.size>20000000)throw Error('รูปต้นฉบับใหญ่เกิน 20 MB');return new Promise((resolve,reject)=>{const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{const scale=Math.min(1,1600/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);const ctx=c.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(img,0,0,c.width,c.height);const imageBase64=c.toDataURL('image/jpeg',.86);URL.revokeObjectURL(url);resolve({imageBase64,mimeType:'image/jpeg'})};img.onerror=()=>{URL.revokeObjectURL(url);reject(Error('อ่านภาพไม่ได้ กรุณาใช้ JPEG หรือ PNG'))};img.src=url});}
function bindFile(){let img=null,generation=0,pending=false;$('#file').onchange=async e=>{const turn=++generation;img=null;pending=true;$('#preview').classList.add('hide');try{const f=e.target.files[0];if(!f)return;const next=await compress(f);if(turn===generation){img=next;$('#preview').src=next.imageBase64;$('#preview').classList.remove('hide')}}catch(e){$('#formError').textContent=e.message}finally{if(turn===generation)pending=false}};return ()=>{if(pending)throw Error('กำลังเตรียมรูป กรุณารอสักครู่');if(!img)throw Error('กรุณาเลือกรูปหลักฐาน');return img};}
function withdrawal(){const requestId=rid();$('#content').innerHTML=hero('บันทึกการใช้เงิน อย่างโปร่งใส','ยอดคงเหลือก่อนถอน '+money(data.availableBalance))+`<form id="form" class="card formgrid"><label>วันที่ถอน<input name="date" type="date" value="${esc(data.today)}" required></label><label>จำนวนเงิน<input name="amount" type="number" min="0.01" step="0.01" max="${Number(data.availableBalance)}" required></label><label class="wide">ใช้ทำอะไร<textarea name="purpose" required maxlength="500"></textarea></label>${fileForm()}<button class="btn wide">บันทึกถอนเงิน</button><div id="formError" class="wide"></div></form>`;const get=bindFile(),f=$('#form');f.onsubmit=async e=>{e.preventDefault();let image;try{image=get()}catch(e){$('#formError').textContent=e.message;return}const b=Object.fromEntries(new FormData(f));if(!await ask('ยืนยันถอนเงิน',`<p>${money(b.amount)} • ${esc(b.purpose)}</p><p class="muted">รายการจะหักจากยอดคงเหลือและแจ้งในกลุ่ม</p>`))return;mutate(f.querySelector('button'),'secWithdraw',{...b,...image,requestId},()=>load('expenses'))};}
function payment(){const b=data.bill,a=data.assignment,bank=data.bank,sub=(data.submissions||[]).find(x=>x.billId===b.id&&['draft','pending','posting'].includes(x.status));$('#content').innerHTML=hero(b.title,`${b.billType==='monthly'?'รายเดือน':'กิจกรรม'} • ${session.memberName} • ครบกำหนด ${day(b.dueDate)}`)+`<div class="cards"><div class="card"><span class="muted">ยอดค้างชำระ</span><div class="amount">${money(Math.max(0,a.amount-a.paidAmount))}</div><div class="divider"></div><h3>${esc(bank.bankName)}</h3><div class="amount" style="font-size:22px">${esc(bank.bankAccountNo)}</div><p>${esc(bank.bankAccountName)}</p><button class="btn soft" id="copy">คัดลอกเลขบัญชี</button></div><div id="proof"></div></div><div id="formError"></div>`;$('#copy').onclick=async()=>{try{await navigator.clipboard.writeText(String(bank.bankAccountNo));$('#copy').textContent='คัดลอกแล้ว ✓'}catch(e){await ask('เลขบัญชี',`<p>กดค้างเพื่อคัดลอก: ${esc(bank.bankAccountNo)}</p>`)}};if(a.status==='paid'||b.status!=='open'){$('#proof').innerHTML=empty('บิลนี้ชำระครบหรือปิดแล้ว');return}if(sub?.status==='draft'){let o={};try{o=JSON.parse(sub.ocr||'{}')}catch(_){}const shouldRead=!Object.keys(o).length&&/รอ OCR|อัปโหลดแล้ว/.test(sub.note||'');draft(sub,shouldRead);return}if(sub){$('#proof').innerHTML=empty('🔎 กำลังรอ Admin ยืนยันเงินเข้า');return}$('#proof').innerHTML=`<form id="form" class="card stack">${fileForm()}<p class="muted">ระบบจะเก็บรูปก่อน แล้วเปิดให้ยืนยันยอดและวันที่ทันที ไม่ต้องรอ OCR</p><button class="btn">อัปโหลดสลิป</button></form>`;const requestId=rid(),get=bindFile(),f=$('#form');f.onsubmit=e=>{e.preventDefault();let image;try{image=get()}catch(e){$('#formError').textContent=e.message;return}mutate(f.querySelector('button'),'secUpload',{...image,requestId,billId},r=>draft(r,true))};}
function draft(r,startOcr=false){let o={};try{o=JSON.parse(r.ocr||'{}')}catch(e){}const hasOcr=Object.keys(o).length>0;$('#proof').innerHTML=`<form class="card stack" id="draft"><span class="tag">${hasOcr?'🔎 OCR อ่านข้อมูลแล้ว':'✓ เก็บรูปแล้ว'}</span><h3>ยืนยันยอดเงินและวันที่</h3><div class="notice ${hasOcr?'':'success'}" id="ocrState">${hasOcr?'ตรวจข้อมูลด้านล่างแล้วส่งต่อได้เลย':'กรอกหรือยืนยันข้อมูลได้ทันที • OCR กำลังช่วยอ่านอยู่เบื้องหลัง'}</div><label>ยอดโอน<input name="amount" type="number" min="0.01" step="0.01" required value="${Number(r.amount)||0}"></label><label>วันที่โอน<input name="date" type="date" required value="${esc(String(r.date||'').slice(0,10))}"></label><p class="muted" id="ocrDetail">ผู้โอน: ${esc(o.senderName||'ยังไม่อ่าน')}<br>ผู้รับ: ${esc(o.receiverName||'ยังไม่อ่าน')}<br>อ้างอิง: ${esc(o.referenceNo||'ยังไม่อ่าน')}</p><label>หมายเหตุ<textarea name="note">${esc(hasOcr?'ตรวจข้อมูลจาก OCR แล้ว':'')}</textarea></label><div class="notice">ถ้าชื่อผู้รับและยอดตรง ระบบจะอนุมัติอัตโนมัติ มิฉะนั้น Admin จะกดอนุมัติให้ทันที</div><button class="btn">ยืนยันและส่งหลักฐาน</button></form>`;const f=$('#draft');let dirty=false;f.querySelectorAll('input,textarea').forEach(el=>el.addEventListener('input',()=>{dirty=true}));f.onsubmit=e=>{e.preventDefault();mutate(f.querySelector('button'),'secSubmit',{...Object.fromEntries(new FormData(f)),id:r.id},()=>load('my-bills'))};if(startOcr)analyzeSlip(r.id,()=>dirty);}
async function analyzeSlip(id,isDirty){const state=$('#ocrState');if(!state)return;try{const result=await api('secAnalyze',{id,requestId:rid()});if(result.status==='approved'){state.className='notice success';state.textContent='ตรวจชื่อผู้รับและยอดตรงกัน • อนุมัติการชำระอัตโนมัติแล้ว';clearViewCache();await ask('ชำระเงินสำเร็จ','<p>ระบบตรวจชื่อผู้รับและยอดตรงกัน จึงบันทึกเงินเข้าแล้ว</p>');await load('my-bills');return}if(result.status!=='draft')return;if(isDirty&&isDirty()){state.className='notice';state.textContent='OCR อ่านเสร็จแล้ว แต่คงค่าที่คุณกำลังกรอกไว้';return}draft(result,false)}catch(e){if(state.isConnected){state.className='notice';state.textContent='OCR อ่านไม่ได้หรือใช้เวลานาน • กรุณายืนยันยอดเงินและวันที่ด้านล่างได้เลย'}}}
function plans(){const h=data.history;$('#content').innerHTML=hero('ตั้งครั้งเดียว ดูแลเป็นรายเดือน','ตรวจแผนที่เปิดใช้งานและเดือนล่าสุดที่สร้างบิล')+(h.items.length?`<div class="cards">${h.items.map(p=>`<div class="card"><span class="tag">${p.status==='active'?'เปิดใช้งาน':'หยุดแล้ว'}</span><h3>${esc(p.title)}</h3><div class="amount">${money(p.amountPerMember)} <small class="muted">/ คน</small></div><p>สร้างวันที่ 23 • ครบกำหนดวันที่ ${esc(p.dueDay)}</p><p class="muted">สร้างล่าสุด: ${esc(p.lastGeneratedMonth||'ยังไม่ถึงรอบสร้าง')}</p><p class="muted">สมาชิก ${String(p.memberIds||'').split(',').filter(Boolean).length} คน</p>${p.status==='active'?`<button class="btn danger" data-stop="${esc(p.id)}">หยุดแผนนี้</button>`:''}</div>`).join('')}</div>`:empty('ยังไม่มีแผนรายเดือน'));document.querySelectorAll('[data-stop]').forEach(btn=>btn.onclick=async()=>{if(await ask('หยุดแผนรายเดือน','<p>บิลที่สร้างไปแล้วจะยังคงอยู่</p>'))mutate(btn,'secStopPlan',{id:btn.dataset.stop,requestId:rid()},()=>load('plans'))});pager(h);}
function safeUrl(v){try{const u=new URL(v);return u.protocol==='https:'?u.href:''}catch(e){return ''}}
function reviews(){const h=data.history;$('#content').innerHTML=hero('ตรวจสลิป แล้วลงบัญชีทันที','เมื่อ Admin กดอนุมัติ ระบบถือว่ายืนยันว่าเงินเข้าแล้วและบันทึกแบบป้องกันยอดซ้ำ')+(h.items.length?`<div class="cards">${h.items.map(r=>`<article class="card"><span class="tag warn">${status(r.status)}</span><h3>${esc(r.memberName)}</h3><p class="muted">บิล ${esc(r.billTitle||r.billId)} • ${day(r.date)}</p><div class="amount">${money(r.amount)}</div><p class="muted">อ้างอิงจากสลิป: ${esc(r.reference||'อ่านไม่ได้')}</p><div class="row wrap"><a class="btn soft" href="${esc(safeUrl(r.proofUrl))}" target="_blank" rel="noopener">เปิดหลักฐาน</a><button class="btn" data-approve="${esc(r.id)}">อนุมัติเงินเข้าทันที</button><button class="btn danger" data-reject="${esc(r.id)}">ไม่ผ่าน</button></div></article>`).join('')}</div>`:empty('ไม่มีสลิปรอตรวจสอบ'));document.querySelectorAll('[data-approve]').forEach(btn=>btn.onclick=async()=>{const r=h.items.find(r=>r.id===btn.dataset.approve);if(await ask('อนุมัติเงินเข้าทันที',`<p><strong>${esc(r.memberName)}</strong> • ${money(r.amount)}</p><p class="muted">การกดยืนยันหมายถึง Admin ตรวจแล้วว่าเงินเข้า ระบบจะลงบัญชีทันทีและกดซ้ำไม่เพิ่มยอดซ้ำ</p>`))mutate(btn,'secReview',{id:r.id,decision:'approve'},()=>load('reviews'))});document.querySelectorAll('[data-reject]').forEach(btn=>btn.onclick=async()=>{if(await ask('ระบุเหตุผลที่ไม่ผ่าน','<label>เหตุผล<textarea id="reason"></textarea></label>'))mutate(btn,'secReview',{id:btn.dataset.reject,decision:'reject',reason:$('#reason').value},()=>load('reviews'))});pager(h);}
function notifications(){const h=data.history,d=data.diagnosis,last=data.lastRun;$('#content').innerHTML=hero('บอตทำงานอยู่ไหม? ดูได้ที่นี่','แยกผลการส่งกลุ่มและรายบุคคล • ไม่ถือว่ารับคำขอเท่ากับอ่านแล้ว')+`<div class="metrics"><div class="metric"><div class="muted">Trigger ที่ตรวจพบ</div><div class="value">${d.triggerCount} / 2</div></div><div class="metric"><div class="muted">ตรวจรายเดือนวันนี้</div><div class="value">${d.monthlyReminderWindow?'อยู่ในรอบ':'นอกรอบ'}</div></div><div class="metric"><div class="muted">รันล่าสุด</div><div>${last?esc(new Date(last.at).toLocaleString('th-TH')):'ยังไม่มีประวัติ'}</div></div></div><div class="card">${h.items.map(r=>`<div class="table-row"><div><span class="tag ${r.status==='failed'?'warn':''}">${esc(status(r.status))}</span><h3>${r.channel==='group'?'กลุ่มใหญ่':'ส่วนตัว'} • ${esc(r.target||'ไม่มี LINE ID')}</h3><p class="muted">${esc(r.billId)} • ${esc(r.day)} • ลอง ${Number(r.attempts)} ครั้ง</p><p class="small">${esc(r.message||'')}</p></div><span class="tag">HTTP ${esc(r.httpCode||'—')}</span></div>`).join('')||'<p>ยังไม่มีประวัติการส่ง</p>'}</div>`;pager(h);}
async function init(){route();if(!IS_LIFF){$('#content').innerHTML=hero('ไก่จิก พร้อมดูแลทีมแล้ว','ดูบิล ส่งหลักฐาน และติดตามการใช้เงินของทีมได้ในที่เดียว')+`<div class="card stack"><h2>ยินดีต้อนรับสู่ SEC1</h2><p class="muted">เข้าสู่ระบบ LINE เพื่อดูข้อมูลตามสิทธิ์ของคุณ</p><a class="btn" href="https://liff.line.me/${CONFIG.liffId}?view=${encodeURIComponent(view)}">เข้าสู่ระบบด้วย LINE</a><p class="small muted">Admin ใช้บัญชีที่ตั้งไว้ใน LINE_ADMIN_USER_IDS</p></div>`;return}$('#content').innerHTML=skeleton();try{await loadSdk();await liff.init({liffId:CONFIG.liffId});route();if(!liff.isLoggedIn()){liff.login({redirectUri:location.href});return}token=liff.getAccessToken();await prepareClientCache();await load(view,1,billId)}catch(e){error(e)}}
function loadSdk(){return new Promise((resolve,reject)=>{if(window.liff)return resolve();const script=document.createElement('script');script.src='https://static.line-scdn.net/liff/edge/2/sdk.js';script.onload=resolve;script.onerror=()=>reject(Error('โหลด LINE ไม่สำเร็จ กรุณาตรวจอินเทอร์เน็ต'));document.head.appendChild(script)})}

function mascot(){return '<img class="chicken" src="assets/c01-regular.svg" alt="ไก่จิก" width="240" height="240">';}
const viewCache=new Map();let cacheNamespace='',uncertainOperation=null;
const READ_ONLY_ACTIONS=new Set(['secRead','secStatus']);
function cacheKey(v,p,id){return [v,p,id||''].join(':');}
function rememberView(key,value){viewCache.delete(key);viewCache.set(key,value);while(viewCache.size>20)viewCache.delete(viewCache.keys().next().value);try{if(cacheNamespace)localStorage.setItem(cacheNamespace,JSON.stringify([...viewCache]));}catch(_){/* Memory cache still works when storage is full. */}}
function clearViewCache(){viewCache.clear();try{if(cacheNamespace)localStorage.removeItem(cacheNamespace)}catch(_){}}
function pendingKey(){return cacheNamespace+':operation';}
function saveOperation(op){uncertainOperation=op;try{if(cacheNamespace){if(op)localStorage.setItem(pendingKey(),JSON.stringify(op));else localStorage.removeItem(pendingKey())}}catch(_){}}
async function prepareClientCache(){try{const sub=liff.getDecodedIDToken?.()?.sub||token,hash=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(CONFIG.liffId+':'+sub));cacheNamespace='sec1-view40:'+Array.from(new Uint8Array(hash),b=>b.toString(16).padStart(2,'0')).join('');const stored=JSON.parse(localStorage.getItem(cacheNamespace)||'[]');if(Array.isArray(stored))for(const [k,v] of stored.slice(-20)){if(v&&v.savedAt&&Date.now()-v.savedAt<604800000&&v.data&&v.session)viewCache.set(k,v)}uncertainOperation=JSON.parse(localStorage.getItem(pendingKey())||'null')}catch(_){/* Never block login because browser cache is unavailable. */}}
function showOperation(){let el=$('#operationStatus');if(!uncertainOperation){if(el)el.remove();return}if(!el){el=document.createElement('div');el.id='operationStatus';el.className='notice pending';$('#content').before(el)}el.innerHTML='<strong>กำลังตรวจผลรายการก่อนหน้า</strong><p>ยังไม่ยืนยันผล กรุณาตรวจสถานะก่อนทำรายการใหม่ เพื่อป้องกันบันทึกซ้ำ</p><button class="btn soft" id="checkOperation">ตรวจสถานะรายการ</button>';$('#checkOperation').onclick=async()=>{const b=$('#checkOperation');b.disabled=true;try{const r=await api('secStatus',{operation:uncertainOperation});if(r.state==='complete'||r.state==='failed'){saveOperation(null);clearViewCache();showOperation();await load(view,page,billId);if(r.state==='failed')await ask('ผลรายการ',`<p>${esc(r.message)}</p>`)}else{el.querySelector('p').textContent=r.message}}catch(e){el.querySelector('p').textContent=e.message}finally{if(b.isConnected)b.disabled=false}};}
async function api(action,body={}){
  const readOnly=READ_ONLY_ACTIONS.has(action),attempts=action==='secRead'?2:1;
  for(let attempt=0;attempt<attempts;attempt++){
    const controller=new AbortController(),timeoutMs=action==='secAnalyze'?12000:(readOnly?30000:240000),timeout=setTimeout(()=>controller.abort(),timeoutMs);
    try{
      const response=await fetch(CONFIG.apiUrl,{method:'POST',signal:controller.signal,cache:'no-store',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,accessToken:token,...body})});
      let out;try{out=await response.json()}catch(_){const err=Error('เซิร์ฟเวอร์ตอบกลับไม่สมบูรณ์ กรุณาลองโหลดใหม่');err.transient=true;throw err}
      if(!out.success){const err=Error(out.message||'ทำรายการไม่สำเร็จ');err.applicationError=true;throw err}return out;
    }catch(e){
      const transient=!e.applicationError;if(readOnly&&transient&&attempt+1<attempts){await new Promise(r=>setTimeout(r,800));continue}
      if(transient){const err=Error(readOnly?'โหลดข้อมูลยังไม่สำเร็จ กรุณากดลองโหลดอีกครั้ง ไม่มีการบันทึกรายการจากการโหลดหน้านี้':'ยังไม่ได้รับผลการบันทึก กำลังตรวจสถานะเดิมโดยไม่ส่งรายการซ้ำ');err.uncertain=!readOnly;err.transient=true;throw err}throw e;
    }finally{clearTimeout(timeout)}
  }
}
async function queuedRead(body,ticket){await new Promise(r=>setTimeout(r,60));if(ticket!==seq){const e=Error('ยกเลิกการโหลดหน้าเก่า');e.obsolete=true;throw e}return api('secRead',body);}
async function load(v,p=1,id=''){
  if(busy)return;const ticket=++seq;view=v;page=p;billId=id;
  const url=new URL(location.href);url.searchParams.delete('liff.state');url.searchParams.set('view',v);if(id)url.searchParams.set('billId',id);else url.searchParams.delete('billId');window.history.replaceState(null,'',url);
  $('#title').textContent=NAMES[v]||'รายละเอียดบิล';const key=cacheKey(v,p,id),cached=viewCache.get(key);
  $('#cacheWarning')?.remove();$('#content').inert=false;$('#updated').textContent='';nav();
  if(cached){session=cached.session;data=cached.data;nav();render();$('#content').inert=true;$('#content').classList.add('validating');$('#updated').textContent='แสดงข้อมูลที่เคยโหลด • กำลังตรวจสอบข้อมูลล่าสุด…';}
  else{$('#content').innerHTML=skeleton();$('#content').classList.remove('validating')}
  showOperation();if(ticket!==seq)return;
  try{
    const out=await queuedRead({view:v,page:p,billId:id,...(cached?.etag?{ifNoneMatch:cached.etag}:{})},ticket);if(ticket!==seq)return;
    if(out.notModified&&!cached)throw Error('ไม่พบข้อมูลแคช กรุณาโหลดใหม่');
    session=out.session;data=out.notModified?cached.data:out.data;rememberView(key,{session,data,etag:out.etag||'',savedAt:Date.now()});
    $('#identity').textContent=(session.isAdmin?'Admin • ':'')+(session.memberName||session.displayName);
    $('#content').inert=false;$('#content').classList.remove('validating');nav();render();showOperation();
    $('#updated').textContent=(out.notModified?'ข้อมูลไม่เปลี่ยน • ตรวจสอบแล้ว ':out.cache==='hit'?'ใช้แคชที่ตรวจข้อมูลแล้ว ':'อัปเดตแล้ว ')+new Date(out.updatedAt).toLocaleTimeString('th-TH');
  }catch(e){if(ticket!==seq||e.obsolete)return;if(cached&&e.transient){session=cached.session;data=cached.data;render();$('#content').inert=true;$('#content').classList.add('validating');const warning=document.createElement('div');warning.id='cacheWarning';warning.className='notice error';warning.innerHTML='ยังตรวจข้อมูลล่าสุดไม่ได้ กำลังแสดงข้อมูลที่บันทึกในเครื่องแบบอ่านอย่างเดียว <button class="btn soft" id="retryCached">ลองใหม่</button>';$('#content').before(warning);$('#retryCached').onclick=()=>load(view,page,billId);$('#updated').textContent='ข้อมูลสำรองในเครื่อง • ยังไม่ยืนยันข้อมูลล่าสุด';showOperation();return}$('#content').inert=false;$('#content').classList.remove('validating');if(e.applicationError){clearViewCache();session=null;$('#nav').innerHTML='';$('#identity').textContent='กรุณาตรวจสอบสิทธิ์ LINE'}error(e);showOperation();}
}
async function mutate(btn,action,body,after){
  if(busy)return;if(uncertainOperation){showOperation();$('#operationStatus')?.scrollIntoView({behavior:'smooth',block:'center'});return}
  busy=true;const old=btn.innerHTML;btn.disabled=true;btn.innerHTML='<span class="spinner"></span> กำลังดำเนินการ';
  const request={...body,requestId:body.requestId||rid()},descriptor={action,requestId:request.requestId,id:request.id||'',billId:request.billId||''};saveOperation(descriptor);
  try{
    let result;try{result=await api(action,request)}catch(e){if(!e.uncertain)throw e;showOperation();const state=await api('secStatus',{operation:descriptor}).catch(()=>null);if(state?.state==='complete')result=state.result;else if(state?.state==='failed'){const failed=Error(state.message);failed.applicationError=true;throw failed}else throw e}
    saveOperation(null);showOperation();busy=false;await after(result);
  }catch(e){busy=false;if(e.applicationError)saveOperation(null);showOperation();const el=$('#formError');if(el)el.innerHTML=`<div class="notice error">${esc(e.message)}</div>`;else if(!uncertainOperation)await ask('ทำรายการไม่สำเร็จ',`<p>${esc(e.message)}</p>`)}
  finally{busy=false;if(btn.isConnected){btn.disabled=false;btn.innerHTML=old}}
}

init();
